[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[colors.bright]
black = "0x585b70"
blue = "0x89b4fa"
cyan = "0x94e2d5"
green = "0xa6e3a1"
magenta = "0xf5c2e7"
red = "0xf38ba8"
white = "0xcdd6f4"
yellow = "0xf9e2af"

[colors.cursor]
cursor = "0xf5e0dc"
text = "0x1e1e2e"

[colors.normal]
black = "0x45475a"
blue = "0x89b4fa"
cyan = "0x94e2d5"
green = "0xa6e3a1"
magenta = "0xf5c2e7"
red = "0xf38ba8"
white = "0xcdd6f4"
yellow = "0xf9e2af"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

[colors.selection]
background = "0xf5e0dc"
text = "0x1e1e2e"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
startup_mode = "Windowed"

[window.padding]
x = 4
y = 4

[keyboard]
